### ISSUE TITLE
Undocumented differences compared to Shiki-Twoslash

### ISSUE THREAD

**Issue by olets** [antfu/shikiji#106]
### Describe the bug

I found the following when trying a migration from [`eleventy-plugin-shiki-twoslash`](https://github.com/shikijs/twoslash/tree/main/packages/eleventy-plugin-shiki-twoslash) to `markdown-it-shikiji`:

- Shikiji is more strict with language names. Shiki-Twoslash will identify the language in
    ````md
    ```ts::my-annotation
    <!-- … -->
    ```
    ````
    as `ts`. Shikiji will error on the unknown language `ts::my-annotation`
- Shikiji does not preserve attributes. Shiki-Twoslash will render
    ````md
    ```js my-attribute
    <!-- … -->
    ```
    ````
    as
    ```html
    <pre class="shiki <theme>" my-attribute
    ```
    and
    ````md
    ```js class="my-class"
    <!-- … -->
    ```
    ````
    as
    ```html
    <pre class="shiki <theme> my-class">…</pre>
    ```
    Shikiji renders both as
    ```html
    <pre class="shiki shiki-themes <theme> [<theme> […]]">…</pre>
    ```
- Shikiji uses `span`s for lines. Shiki-Twoslash uses `div`s. When migrating, can expect to have to add display:block to lines.
- Shikiji adds `tabindex="0"` to its `pre`s. Shiki-Twoslash doesn't. I'd be interested to hear the rationale, not something I've seen done.
- Shikiji by default has a block gap between code lines. Shiki-Twoslash doesn't. (I'm not sure where that's coming from, but I only investigated for a few minutes). Means that inline codeblock borders cannot be styled via lines (e.g. `code .line { border-left: 1px solid red }`)

I've only used Shiki in the context of Shiki-Twoslash (via the Eleventy plugin, and via the Shiki-Twoslash playground), and haven't dug into the implementation there. Maybe this is all expected? If so I'd be happy to PR an update to the compatibility docs page.

### Reproduction

Lmk a good way to provide one

### System Info

```Shell
% pnpm envinfo --system --binaries --browsers

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 301.44 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.asdf/installs/nodejs/18.17.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.asdf/installs/nodejs/18.17.1/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It would be hard to help/discuss, especially since we don't have a 11ty integration at this moment, and it's hard to compare as you don't know if a certain feature comes from shiki, twoslash, the plugin, or 11ty to talk about the difference. 

> ```js class="my-class"

I am sure this is some additional feature offered somewhere, as there is no standard way to interop this meta, and it's out-of Shikiji's responsibility to introduce a convention for you (likely ppl would prefer different conventions).

> tabindex="0"

It's Shiki's behaviour: https://github.com/shikijs/shiki/blob/873221fabea832abc6c9168d92aa07a362f43e74/packages/shiki/src/renderer.ts#L8. I don't mind to introduce a breaking change to remove it by default tho. But On the contrary, this is actually aligned (idk why it was not working for you).

> linebreaks

You can use https://shikiji.netlify.app/packages/transformers#transformerremovelinebreak

---

But again, I'd suggest you to go deeper and compare apple with apple (like rehype-plugin vs rehype-plugin, with other tools to be the same), and send separate issue for each misalignment so we could handle them one by one. Thank you.

**Comment by olets** [comment]
> we don't have a 11ty integration at this moment

FYI you do for Eleventy v3 (still in alpha) 🎉  By default, Eleventy uses [markdown-it and markdown-it plugins](https://www.11ty.dev/docs/languages/markdown/), and [v3 supports ESM](https://www.11ty.dev/blog/canary-eleventy-v3/#new-features-and-a-short-upgrade-guide). I've confirmed `markdown-it-shikiji` works directly.

> linebreaks

Cool thanks! IMO that's worth a mention in the compatibility docs. Lmk if you'd like me to PR it.

---

Did some digging. These next two may come down to https://github.com/shikijs/twoslash vs https://github.com/twoslashes/twoslash. Until today I was unaware of twoslashes/twoslash. I see you're very active in twoslashes/twoslash. Don't know if you're interested in parity with / taking ideas from shikijs/twoslash. If so, I'll open separate issues. Lmk.

> meta

Found it.

shikijs/twoslash's shiki-twoslash uses [fenceparser](https://github.com/frencojobs/fenceparser)
- https://github.com/shikijs/twoslash/blob/fc5463da86c67ac9d382cbcbbfa1f8d665555fe4/packages/shiki-twoslash/src/utils.ts#L3
- and in their [remark-shiki-twoslash](https://github.com/shikijs/twoslash/tree/fc5463da86c67ac9d382cbcbbfa1f8d665555fe4/packages/remark-shiki-twoslash) which both shikijs/twoslash's [Shiki-Twoslash Playground](https://shikijs.github.io/twoslash/playground) and all [shikijs/twoslash's other plugins](https://github.com/shikijs/twoslash/tree/fc5463da86c67ac9d382cbcbbfa1f8d665555fe4/packages) depend on: https://github.com/shikijs/twoslash/blob/fc5463da86c67ac9d382cbcbbfa1f8d665555fe4/packages/remark-shiki-twoslash/src/index.ts#L104-L124

twoslashes/twoslash's twoslash does not use fenceparser.

> tabindex

Found it, it's Shiki's behavior (so twoslashes/twoslash's) but not shikijs/twoslash's Shiki-Twoslash's https://github.com/shikijs/twoslash/blob/fc5463da86c67ac9d382cbcbbfa1f8d665555fe4/packages/shiki-twoslash/src/renderers/plain.ts#L39

**Comment by antfu** [comment]
We will slowly migrate packages from https://github.com/shikijs/twoslash to adopt the new format. For now I guess you will need to figure out the migration path on your own. Also feel free to open issue for each misalignment one by one later in https://github.com/shikijs/shiki
