### ISSUE TITLE
`transformerMetaWordHighlight` highlight is not working when word includes symbols

### ISSUE THREAD

**Issue by sadeghbarati** [antfu/shikiji#110]
### Describe the bug

Please first take a look at [rehype-pretty-code](https://rehype-pretty-code.netlify.app/#word-highlighting) word highlighting section

I want the same behavior with **Shikiji** but it seems `transformerMetaWordHighlight` only works with words without symbols

Thanks for your work ❤️ 

### Reproduction

https://stackblitz.com/edit/vite-rfm8dh

### System Info

```Shell
System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 4.66 GB / 15.83 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fuma-nama** [comment]
Perhaps we can include other common symbols like `" | . - ,`. We will not support edge cases where the word is separated into multiple tokens

**Comment by antfu** [comment]
Still some refactor to do to support multiple token highlight

**Comment by fuma-nama** [comment]
I am willing to submit a fix

**Comment by antfu** [comment]
Great, here is a reference in twoslash integration: https://github.com/antfu/shikiji/blob/4b61e33cd26a917dbc0e8764c4b4c17b619c77e2/packages/shikiji-twoslash/src/core.ts#L202-L228

**Comment by fuma-nama** [comment]
> I think [vuejs/vitepress#3503](https://github.com/vuejs/vitepress/issues/3503) is also related to this. There, the text that's being matched against the regex is not the whole line instead individual tokens 👀 The comments like `// [!code error]` don't work if they are not entirely in the same text node.

That is caused by the limitation of design rather than the transformer itself, adding comments after attributes is not valid in Vue. Therefore, you'll see a weird highlighting here:

```vue
<template>
  <div
    class="container max-w-250 mx-a my-10 min-h-250 vp-doc p4" // something
    of-hidden
  >
    <ShikijiMiniPlayground />
  </div>
</template>
```

Writing this in real code even gives you syntax errors, which is not supposed to work.

**Comment by antfu** [comment]
@brc-dd Feel free to open an issue on https://github.com/shikijs/shiki and we could discuss what would be the solution for that :)
