### ISSUE TITLE
Support for inline code

### ISSUE THREAD

**Issue by fuma-nama** [antfu/shikiji#111]
### Clear and concise description of the problem

For now, shikiji is not intended to support inline code blocks, as transformers, integrations, and many others are not supposed to process inline code. 

I want to highlight an inline code block, for example: `console.log("Hello World")`. 

### Suggested solution

Allow us to specify language via `{js} console.log("Hello World")`, and enable inline code processing for each integration.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Shikiji itself is focused on highlighting itself, while you can see quite many highlighter integrations built on top of Shikiji **does support inline highlights**. For example, 

- https://github.com/expressive-code/expressive-code
- https://github.com/atomiks/rehype-pretty-code
- https://github.com/nuxt/content

Basically, you just treat the inline code as a 1-line code and get the first line element from the HAST.

If you mean the official markdown-it / rehype plugins, I am happy to have it as an optional feature. But to do that, we need to research existing syntaxes and find one that makes sense, as it's not a standard markdown syntax and might conflict with other integrations.

**Comment by fuma-nama** [comment]
Thanks! That makes sense
