### ISSUE TITLE
codeToHtml requires theme option

### ISSUE THREAD

**Issue by dpi** [antfu/shikiji#15]
### Describe the bug

First off, thank you for this project! It simplifies things significantly. (

I'm not entirely sure if this is a bug or an accident it worked, but:

When switching from the original project to Shikiji:

Invoking codeToHtml with only `{ lang: "php"}` worked fine originally, but after switching the following is produced in console, wherein the code is also not formatted:

> Error: [shikiji] Invalid options, either `theme` or `themes` must be provided

Adding `theme` to the `codeToHtml` invocation fixes things `{ lang: "php", theme: 'github-dark'}` .

### Reproduction

https://github.com/dpi/shikiji-theme-bug

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 61.70 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Safari: 16.5.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's an intentional breaking change. If you want shiki's original behavior, you can try https://github.com/antfu/shikiji/tree/main/packages/shikiji-compat

**Comment by dpi** [comment]
Thanks, I dont know how I missed its mention in https://github.com/antfu/shikiji#breaking-changes-from-shiki
