### ISSUE TITLE
Can rehypeShikiji customize meta?

### ISSUE THREAD

**Issue by AntzyMo** [antfu/shikiji#16]
### Clear and concise description of the problem

\```js name="test" copy
console.log('test')
\```

What if I want to get the name parameter?

### Suggested solution

I hope that the parameters in the meta can be exposed

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, if you have any idea about the API design, feel free to bring it up here or make a PR.
