### ISSUE TITLE
Proposal: allow setting CSS variables `var(--my-var)` as `settings.foreground` since `shikiji-compat` doesn't replace `css-variables` theme colors with `var(--shiki-color-...)` variables

### ISSUE THREAD

**Issue by B2o5T** [antfu/shikiji#18]
### Clear and concise description of the problem

`shiki` replace colors for `css-variables` theme

https://github.com/shikijs/shiki/blob/f705b0fc7c8a31bfadd40322db86421cccc31c6f/packages/shiki/src/highlighter.ts#L51-L63

### Suggested solution

do the same

### Alternative

or it will be better to write CSS variables directly instead of color 
<img width="399" alt="image" src="https://github.com/antfu/shikiji/assets/7361780/653d5d8d-b0a1-4ac1-884a-7c7703ea1c44">

> [!NOTE]
>
> Found another user wanted the same behaviour in shiki https://github.com/shikijs/shiki/issues/33#issuecomment-1119359692

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Shikiji didn't implement the `css-variables` theme handling, I am not sure if we should even drop it in favor of our multiple themes approach. Ultimately, the `css-variables` theme is not a good fit for Shiki as it discards a lot of fine details shiki has (which I see it's the main benefit of using shiki) and fallback to something similar to prism.js or highlight.js
