### ISSUE TITLE
Downstream bug in nuxt/mdc: Highlight specific lines does not work anymore in dark mode due to !important

### ISSUE THREAD

**Issue by PatrikBird** [antfu/shikiji#19]
### Describe the bug

Hey ❤️ 

I'm using `nuxt/content` and since its using this package now via `nuxt/mdc` I hope I found the right place to address this.

As shown in the readme in the project: https://github.com/antfu/shikiji#class-based-dark-mode
```
<style>html.dark .shiki span {color: var(--shiki-dark) !important;background: var(--shiki-dark-bg) !important;font-style: var(--shiki-dark-font-style) !important;font-weight: var(--shiki-dark-font-weight) !important;text-decoration: var(--shiki-dark-text-decoration) !important;}</style>
```
The `!important` tag in `background: var(--shiki-dark-bg) !important;` break the highlight feature in `nuxt/mdc` as it makes it impossible to highlight certain lines in code blocks if dark mode is enabled.

In this case (I hope) a quick example is enough instead of a full reproduction:

Example.md:
\```ts {1}
let foo = 'bar'
\```

The `{1}` adds a `highlight` class to line 1 which enables specific styles for the lines specified.
This won't work anymore as it's been overwritten with `!important` as mentioned above.

If I manipulate my rendered html by removing the mentioned !important tag, it seems to work as expected.

cheers!

### Reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Would you create an issue in nuxt/content with a minimal reproduction? It might be fixable there.
