### ISSUE TITLE
Add plain text language support

### ISSUE THREAD

**Issue by qhanw** [antfu/shikiji#24]
### Clear and concise description of the problem

when I use the code in the blow, shikiji gives a clue in the second picture.
<img width="298" alt="image" src="https://github.com/antfu/shikiji/assets/10607656/1d40c402-692d-4a48-a6c6-30dc52ec18d9">

<img width="632" alt="image" src="https://github.com/antfu/shikiji/assets/10607656/3a636607-3938-4dd1-8b3a-63f7f736759e">

### Suggested solution

hope that shikiji surpport the plian text language

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Well 👀

https://github.com/antfu/shikiji/blob/c70e262796f1cbddd67c65c1a3a5ee1707f05233/packages/shikiji/src/core/utils.ts#L4

**Comment by qhanw** [comment]
Is there needing to consider of the type of `plain`, which is often used? eg:
```ts
 return !lang || ['plaintext', 'plain', 'txt', 'text'].includes(lang) 
```

**Comment by qhanw** [comment]
> Well 👀
> 
> https://github.com/antfu/shikiji/blob/c70e262796f1cbddd67c65c1a3a5ee1707f05233/packages/shikiji/src/core/utils.ts#L4

Is there needing to consider of the type of plain, which is often used? eg:
```ts
 return !lang || ['plaintext', 'plain', 'txt', 'text'].includes(lang) 
```

**Comment by antfu** [comment]
Do you have a reference for using `plain` in other syntax highlighter or so? Or I'd prefer to keep the current list as-is, as `plain` is just a adjective that can be ambiguous, say "plain javascript" 👀

**Comment by antfu** [comment]
Ok, making sense, let's align with it :)
