### ISSUE TITLE
Docs / example on how to load custom themes via JSON files

### ISSUE THREAD

**Issue by DavidTParks** [antfu/shikiji#27]
### Clear and concise description of the problem

Hi there,

I'm unsure how to load custom themes via JSON.  (For example, https://github.com/wesbos/cobalt2)

For example, I am using Shikiji as follows

```
import { bundledLanguages, bundledThemes, getHighlighter, Highlighter } from 'shikiji';

let highlighter: Highlighter

export type Theme = keyof typeof bundledThemes
export type Language = keyof typeof bundledLanguages
interface IHighlight {
    codeString: string;
    theme: Theme
    language: Language
}


export async function highlight({
    codeString,
    theme = "dracula-soft",
    language = "tsx"
}: IHighlight) {
    highlighter = await getHighlighter({
        themes: [theme],
        langs: [language],
    })

    const [themedTokens, hast] = await Promise.all([
        highlighter.codeToThemedTokens(codeString, {
            lang: language,
            theme: theme
        }),
        highlighter.codeToHast(codeString, {
            lang: language,
            theme: theme,

        }),
    ])


    return {
        themedTokens,
        hast,

    }
}
```

I've tried to import themes and then use `toShikiTheme` to no avail (when I try to pass in a custom theme name, it says it's not supported)

Is it possible with this lib to load custom themes? If so, it would be helpful to see an example of it. 

### Suggested solution

Provide an example or indication of if loading themes (not in BUNDLED_THEMES) is possible. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by uncenter** [comment]
You can use this guide from the shiki repo: https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki

**Comment by alvarosabu** [comment]
@uncenter but that guide is for custom languages not custom themes
