### ISSUE TITLE
Tree-Sitter usage

### ISSUE THREAD

**Issue by hinogi** [antfu/shikiji#3]
### Clear and concise description of the problem

Maybe instead of using a textmate dialect of some sorts, https://tree-sitter.github.io/tree-sitter/ could be used instead.

### Suggested solution

https://tree-sitter.github.io/tree-sitter/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up, but it's out-of-scope.
