### ISSUE TITLE
Improved & well-documented version of `codeToTokensWithThemes`

### ISSUE THREAD

**Issue by fuma-nama** [antfu/shikiji#37]
### Clear and concise description of the problem

Currently, I'm trying to use Shikiji to add animated code blocks to a landing page. However, I can't find anything regarding to light/dark theme support for the `codeToThemedTokens` method. It seems to me that this is not yet a supported feature in Shikiji.

it's useful for rendering code blocks in React.js or other similar libraries, otherwise you can only get this feature with `hast`/`markdown-it`.

### Suggested solution

The `codeToTokensWithThemes` method does support multiple themes, but it isn't convenient to use. It returns an array of `[color: string, theme: string, tokens: ThemedToken[][]]` (according to typescript declarations), which need to be flattened into one before rendering them. 

I hope there is a more simplified method for this, for instance, we can flatten the tokens under the hood:

```ts
interface MultipleThemedToken {
    color: {
        [theme: string]: string
    }
}
```

```ts
const tokens: MultipleThemedToken[][] = highlighter.codeToTokensWithThemes(code, { ... })
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
The reason we were doing this is because we want to be compatible with the `ThemedToken` interface (altering `color` from `string` to object will break the other tool), while merging all colors into `color` as a flat string might not be flexible enough.

Can you elaborate more about your usage? If it's valid concern, we could introduce an additional utility for it maybe.

**Comment by fuma-nama** [comment]
Since the `codeToHast` and `codeToHtml` methods both support multiple(light/dark) themes, `codeToThemedTokens` should have supported it too, for a better API consistency.

Takes an example of a custom code block in React.js:
```tsx
export function CodeBlock({ code, lang, className, ...props }: CodeBlockProps) {
  const tokens = useMemo(
    () =>
      highlighter.codeToThemedTokens(code, {
        lang
      }),
    [code]
  )

  return (
    <Pre className={cn('bg-black', className)} {...props}>
      <code className="grid">
        {tokens.map((token, i) => (
          <span data-line key={i}>
            {token.map((s, j) => (
              <span key={j} style={{ color: s.color }}>
                {s.content}
              </span>
            ))}
          </span>
        ))}
      </code>
    </Pre>
  )
}
```

Obviously if we use `codeToTokensWithThemes` here, we must preprocess the returned array on our own, to combine to all variants of a node into one. Otherwise, the simplest solution is to render a code block for individual themes, which is not ideal in terms of bundle size. 

Although I ended up implementing my own function to flatten nodes, the `codeToTokensWithThemes` API itself is not well-documented and straightforward enough (feels like a hacky way to me). Would appreciate it if there’s an additional utility to make it more convenience.

**Comment by fuma-nama** [comment]
That would be a great solution, I initially missed it because `codeToThemedTokens` seemed to be more straightforward for me when comes to be rendering and animating it. Hast nodes are not typed and I was unsure of its properties, they are pretty enough for normal code blocks though
