### ISSUE TITLE
Issues with markdown-it-shikiji update

### ISSUE THREAD

**Issue by adamdehaven** [antfu/shikiji#44]
### Describe the bug

After following the new enhancements from https://shikiji.netlify.app/packages/markdown-it#fine-grained-bundle, a couple things I'm noticing after trying it out via  https://github.com/antfu/shikiji/pull/42

### Shikiji is required as a devDependency

In order to get the imports to properly resolve (at least in my `pnpm` project) I need to explicitly run `pnpm add -D shikiji`. I'm guessing this should be added to the docs for the `markdown-it` plugin, in the `Fine-grained Bundle` docs section.

![image](https://github.com/antfu/shikiji/assets/2229946/3b8faf95-e285-483e-8ba1-f0059339c22b)

### `fromHighlighter` import path

I had to use an import path like this instead of what's in the docs

```typescript
import { fromHighlighter } from 'markdown-it-shikiji' // works

import { fromHighlighter } from 'markdown-it-shikiji/core' // TypeScript complains
```

### Type mismatch when using `fromHighligher`

If I utilize the example provided in the docs, I get the following type error:

```
Argument of type 'HighlighterCore' is not assignable to parameter of type 'HighlighterGeneric<any, any>'.
```

As seen here:
![image](https://github.com/antfu/shikiji/assets/2229946/9d2b04fc-0cf6-45c5-a6f8-3f2ab7b078c1)

based on this usage:

```typescript
import { fromHighlighter } from 'markdown-it-shikiji'
import { getHighlighterCore } from 'shikiji/core'
import { getWasmInlined } from 'shikiji/wasm'
import MarkdownIt from 'markdown-it'

const highlighter = await getHighlighterCore({
  themes: [
    import('shikiji/themes/github-light.mjs'),
    import('shikiji/themes/github-dark.mjs'),
  ],
  langs: [
    import('shikiji/langs/typescript.mjs'),
  ],
  loadWasm: getWasmInlined,
})

md.value = MarkdownIt({
  html: false, 
  xhtmlOut: true, 
  linkify: true, 
  breaks: true, 
  typographer: true, 
  quotes: '“”‘’',
})
  .use(fromHighlighter(highlighter, { // Type Error Here
    themes: {
      light: 'github-light',
      dark: 'github-dark',
    },
  }))
```

### Reproduction

above

### System Info

```Shell
//
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
TypeScript seems to be a setup issue, can you create a reproduction repo so I can have a look?

**Comment by adamdehaven** [comment]
@antfu [here you go](https://github.com/Kong/markdown/pull/2)

**Comment by antfu** [comment]
Thanks, but there are too many things involved. A **minimal reproduction**, please.

**Comment by adamdehaven** [comment]
😂 I definitely gave you the wrong link; sorry about that. I'll get a minimal repo set up this weekend. 

Functionally things seem to work perfectly other than the type issue and the line highlighting.

**Comment by adamdehaven** [comment]
Sorry about the wrong reproduction link - I've put together [a much simpler example on CodeSandbox](https://codesandbox.io/p/devbox/markdown-it-repro-fff88h?file=%2Fsrc%2Fcomponents%2FMarkdownUi.vue%3A66%2C25&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq7he6p700073b6ib0yp9hh8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq7he6p600023b6iyjdodyf1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq7he6p600043b6ifsv4sf4s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq7he6p600063b6itdmw8c2p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50.25575447570333%252C49.74424552429667%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq7he6p600023b6iyjdodyf1%2522%253A%257B%2522id%2522%253A%2522clq7he6p600023b6iyjdodyf1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq7j8ch100023b6hiyq5cenk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A66%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A66%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FMarkdownUi.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq7j8ch100023b6hiyq5cenk%2522%257D%252C%2522clq7he6p600063b6itdmw8c2p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq7he6p600053b6ivansj40y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq7he6p600063b6itdmw8c2p%2522%252C%2522activeTabId%2522%253A%2522clq7he6p600053b6ivansj40y%2522%257D%252C%2522clq7he6p600043b6ifsv4sf4s%2522%253A%257B%2522id%2522%253A%2522clq7he6p600043b6ifsv4sf4s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq7he6p600033b6ixpwm1ldv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq7he6p600033b6ixpwm1ldv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

In putting this together, I actually figured out everything other than the TypeScript error for the `highlighter` mentioned above.

The line highlighting was caused by another plugin; the leading/trailing `{` `}` default characters from `markdown-it-attrs`.

**Comment by adamdehaven** [comment]
On the type imports, the `highlighter` actually resolves correctly if I use this:

```typescript
import { fromHighlighter } from markdown-it-shikiji/core';
```

but then I get an import error:

```markdown
Cannot find module 'markdown-it-shikiji/core' or its corresponding type declarations.
```

**Comment by antfu** [comment]
If you change `"moduleResolution": "Bundler"` in your tsconfig it would work. I also have added the metadata for legacy resolution to work as well, while I would still recommend you to use `Bundler`, in the next version `Node` should work as well.

**Comment by adamdehaven** [comment]
Derp yep. I had originally just reused my tsconfig from another lib. Sorry for the noise; the added metadata also clears it up as-is
