### ISSUE TITLE
Example 404 not found?

### ISSUE THREAD

**Issue by NullVoxPopuli** [antfu/shikiji#46]
### Describe the bug

![image](https://github.com/antfu/shikiji/assets/199018/c4e64d70-b884-4103-9e08-511ffcf8d90b)

### Reproduction

Visit https://shikiji.netlify.app/, select Glimmer TS

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Examples are loaded from https://github.com/shikijs/shiki/tree/main/packages/shiki/samples, where glimmer-ts.sample is missing. While I don't really know what Glimmer is and what's the difference between normal js/ts. If you have some examples, feel free to send PRs to  https://github.com/shikijs/shiki. Thanks.

Closing as this is an upstream issue.

**Comment by NullVoxPopuli** [comment]
Can we reopen this?
It looks like shiki uses the file extensions, rather than the grammar name:

"Glimmer TS" here: https://github.com/shikijs/shiki/blob/main/packages/shiki/samples/gts.sample
"Glimmer JS" here: https://github.com/shikijs/shiki/blob/main/packages/shiki/samples/gjs.sample

**Comment by antfu** [comment]
You could send a PR to shiki and rename those examples.
