### ISSUE TITLE
Need a getLanguage function?

### ISSUE THREAD

**Issue by doroved** [antfu/shikiji#47]
### Clear and concise description of the problem

Case: I am using the answer from OpenAI, last time I tried shikiji, it did not recognize some programming languages, resulting in an error.
Here is an example:

```js
const code = await codeToHtml('const a = 1', { lang: 'jsw', theme: 'vitesse-dark' })
```
```
Unhandled Promise Rejection: Error: [shikiji] Language `jsw` is not built-in.
```

### Suggested solution

In `highlight.js` there is a function `getLanguage` that allows us to check if a programming language exists, if it doesn't, we can assign `plaintext`
```js
const language = hljs.getLanguage(lang) ? lang : 'plaintext'
```
I suggest creating a `getLanguage` function or better yet, handling this situation inside shikiji to avoid a bug that breaks the UI

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://github.com/antfu/shikiji/blob/a5ae95eee81d3ef25b2142795e88443e91d31da9/packages/shikiji-core/src/types.ts#L128-L137

Is this enough for your use case?

**Comment by antfu** [comment]
`highlighter.getLoadedLanguages()` - please read them more carefully or try a few more beforehand.

**Comment by antfu** [comment]
The underlying tech stack requires Shikiji to be async there is no workaround. If you want to use it in the client side, you could share your highlighter instance across components to avoid loading every time.
