### ISSUE TITLE
Twoslash popup is not fully displayed due to the `overflow: hidden` of ancestor elements

### ISSUE THREAD

**Issue by shigma** [antfu/shikiji#60]
### Describe the bug

![image](https://github.com/antfu/shikiji/assets/33423008/9004bf0e-a2c2-41c3-b705-d79f75fcc926)

Is there a way to make it show the full popup on hover?

### Reproduction

https://shikiji.netlify.app/packages/twoslash

### System Info

```Shell
N/A
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I am not sure how to fix this properly without JS
