### ISSUE TITLE
Extra leading space in `span`s containing TypeScript types causes underlines to start early

### ISSUE THREAD

**Issue by velut** [antfu/shikiji#65]
### Describe the bug

When converting TypeScript code to HTML, Shikiji creates a `span` that contains a leading space followed by the type name, for example `<span> LogLevelStrings</span>`. This behavior differs from Shiki which uses one `span` for the space and another one only for the type name.

Ultimately, this bug causes some themes, for example `monokai`, to be applied incorrectly since the underline under the type name starts early, being present also under the space.

> Packages versions.
```
shiki: 0.14.7
shikiji: 0.9.12
```

> Highlighting code with Shiki.
```js
// shiki.cjs
const shiki = require("shiki");

shiki
  .getHighlighter({
    theme: "monokai",
  })
  .then((highlighter) => {
    console.log(
      highlighter.codeToHtml(`type LogLevelStrings = keyof typeof LogLevel;`, {
        lang: "ts",
      })
    );
  });
```

> Highlighting code with Shikiji.
```js
// shikiji.mjs
import { getHighlighter } from "shikiji";

const highlighter = await getHighlighter({
  themes: ["monokai"],
  langs: ["typescript"],
});

const code = highlighter.codeToHtml(
  "type LogLevelStrings = keyof typeof LogLevel;",
  {
    lang: "typescript",
    theme: "monokai",
  }
);

console.log(code);
```
> HTML output from Shiki and Shikiji.
```html
<!-- Shiki -->
<pre
  class="shiki monokai"
  style="background-color: #272822"
  tabindex="0"
><code><span class="line"><span style="color: #66D9EF; font-style: italic">type</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E; text-decoration: underline">LogLevelStrings</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">keyof</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">typeof</span><span style="color: #F8F8F2"> LogLevel;</span></span></code></pre>

<!-- Shikiji -->
<pre
  class="shiki monokai"
  style="background-color: #272822; color: #f8f8f2"
  tabindex="0"
><code><span class="line"><span style="color:#66D9EF;font-style:italic">type</span><span style="color:#A6E22E;text-decoration:underline"> LogLevelStrings</span><span style="color:#F92672"> =</span><span style="color:#F92672"> keyof</span><span style="color:#F92672"> typeof</span><span style="color:#F8F8F2"> LogLevel;</span></span></code></pre>
```

> HTML output differences visualized.

![diff](https://github.com/antfu/shikiji/assets/12040076/af77fe6a-5fd9-44ad-afa3-382a2ab15fbe)

> Bug reproduced on Shikiji Playground by selecting TypeScript and Monokai; type names after `enum`, `type` and `key:` are affected.

![shikiji](https://github.com/antfu/shikiji/assets/12040076/e15b4ed0-f7c9-4a0e-a003-282d67e00155)

> VSCode rendering the same playground code with Monokai.

![vscode](https://github.com/antfu/shikiji/assets/12040076/b5828eb5-5075-48af-8420-a90b36a216a0)

### Reproduction

https://shikiji.netlify.app

### System Info

```Shell
System:
    OS: Linux 6.6 Fedora Linux 38 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 10.18 GB / 15.51 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - /run/user/1000/fnm_multishells/28509_1703779162622/bin/node
    npm: 10.2.3 - /run/user/1000/fnm_multishells/28509_1703779162622/bin/npm
    pnpm: 8.12.1 - ~/.bun/bin/pnpm
    bun: 1.0.20 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This was an optimization trying to provide smaller HTML as possible, where you can turn it off by setting `mergeWhitespaces: false`.

I made the fix to not merge them when the underlined style is presented. Thanks

**Comment by velut** [comment]
Thanks!
