### ISSUE TITLE
Additional types for ThemeRegistrationResolved

### ISSUE THREAD

**Issue by gdomingu** [antfu/shikiji#74]
### Clear and concise description of the problem

I noticed that `'hcLight'` and `'hcDark'` are not included in the [list of types](https://github.com/antfu/shikiji/blob/main/packages/shikiji-core/src/types.ts#L383) for ThemeRegistrationResolved. 

Wondering if we could add that? 

### Suggested solution

https://github.com/antfu/shikiji/pull/73

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Would you elaborate more on why they are needed?

**Comment by gdomingu** [comment]
These are two types are included for high contrast themes from VS code. https://github.com/microsoft/vscode/blob/0a08e6fdcd514741ceb679fb38c746550b5aabf3/src/vs/platform/theme/common/theme.ts#L12-L13

**Comment by antfu** [comment]
I knew. But it doesn't explain why you need it. High-contrast or not, it might make sense to VS Code as an editor. But we are only focusing on syntax highlighting, where the `type` is used to infer the default background color. Contrasty is presented in the colors themselves.

**Comment by gdomingu** [comment]
I think it is needed for compatibility with VS code themes. If someone exports a high contract theme from VS code and tries to pass it into shikiji they will get a type error. One of the main selling points of this library is the compatibility with VS code themes.

**Comment by gdomingu** [comment]
These themes
https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/hc_light.json
https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/hc_black.json

But I notice that type doesn't seem to be present on those JSON files. But shows up when you export the theme in VS code.

**Comment by antfu** [comment]
https://github.com/antfu/shikiji/pull/73#issuecomment-1890927294
