### ISSUE TITLE
Setting up fine-grained highlighter from web bundle bundles all themes

### ISSUE THREAD

**Issue by schardev** [antfu/shikiji#77]
### Describe the bug

I want to setup a fine grained bundle for cloudflare worker but want to support all the languages from the web bundle with only one theme. I did something like this:

```ts
import { getHighlighterCore, bundledLanguages } from 'shikiji/bundle-web.mjs';
import githubDarkDimmed from 'shikiji/themes/github-dark-dimmed.mjs';

const coreHighlighter = await getHighlighterCore({
	themes: [githubDarkDimmed],
	langs: Object.values(bundledLanguages),
});

export default {
	async fetch(request: Request): Promise<Response> {
		const body = await request.text();
		const html = coreHighlighter.codeToHtml(body, { theme: githubDarkDimmed, lang: 'html' });
		return new Response(html);
	},
};
```

Doing something like above works but it also bundles all themes. See `dist/index.js` file after running `pnpm wrangler deploy --dry-run --outdir dist` to confirm.

### Reproduction

As described above.

### System Info

```Shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 10.60 GB / 14.99 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.local/share/pnpm/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - ~/.local/share/pnpm/npm
    pnpm: 8.13.1 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.109
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Well, you are actually mixing the bundled usage with fine-grained. We can't create bundles for every case, and that is why we allow you to compose on your own. The web bundle is more like a convenience or showcasing, if you want more control, you need to bundle the langs you own as well.
