### ISSUE TITLE
Improve In-Browser Markdown Processing Speed with Caching

### ISSUE THREAD

**Issue by wststone** [antfu/shikiji#79]
### Clear and concise description of the problem

In the current implementation of the project, real-time markdown processing in the browser suffers from performance issues due to the absence of result caching for code highlighting. Each keystroke triggers a re-computation and re-loads the grammar, which is not efficient, particularly when dealing with unchanged or static content. This repetitive processing leads to suboptimal performance, especially in applications where real-time content updates are frequent.

![image](https://github.com/antfu/shikiji/assets/42225395/18a5860c-6b07-45da-921d-c3f4f73be8f7)

### Suggested solution

Some sort of caching mechanism that retains the results of previous highlight transformations result in memory. This is especially useful when building ai apps, as the previous output (streamed content) will not need to be transformed again. This should significantly reduce unnecessary computations and improve the responsiveness of the application.

Example Code

```ts
export const rehypeShikijiFromHighlighter: Plugin<
	[
		HighlighterGeneric<any, any>,
		RehypeShikijiCoreOptions & {
			cache?: Map<string, Root>;
		}
	],
	Root
> = function (highlighter, options) {
	const {
		highlightLines = true,
		addLanguageClass = false,
		parseMetaString,
		...rest
	} = options;

	const prefix = "language-";
	const cache = options.cache;
	return function (tree) {
		visit(tree, "element", (node, index, parent) => {
            // other code
			const code = toString(head);
            // check and reuse cache
			if (cache && cache?.has(code)) {
				parent.children.splice(index, 1, ...cache?.get(code).children);
				return;
			}
                        
			try {
				const fragment = highlighter.codeToHast(code, codeOptions);
                // write to cache
				cache?.set(code, fragment);
				parent.children.splice(index, 1, ...fragment.children);
			} catch (error) {
				if (options.onError) options.onError(error);
				else throw error;
			}
		});
	};
};
```

### Alternative

Maybe also offload this to another thread using webworker? not sure this is a good idea

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by wststone** [comment]
> Sure, PR welcome :)

Adding a cache to `rehypeShikiji` should be pretty doable like in the snippet I showed. But i'm not very familiar with textmate's internal implementation as to how to cache the result of `_loadgrammer`, any guidance on where to look in the source code and how to optimize it, would adding an cache option on the top level in `gethighlighter` a good idea?

**Comment by antfu** [comment]
Considering there are multiple layers to cache (code-hast cache, code-html cache, transformers cache, etc.), I think it's better to not implement the cache in core, but in the integrations instead (e.g., the remark plugin etc.). Also in mind that we might need to allow users to provide custom cache implementation like LRU, otherwise it might lead to memleak.

**Comment by wststone** [comment]
I've just submitted a PR here: https://github.com/antfu/shikiji/pull/80

For the moment, I haven't found a way to optimize or cache the grammar loading without touching the core, especially as it's invoked from the top level on each real-time render.
