### ISSUE TITLE
code block bg parm

### ISSUE THREAD

**Issue by blackPeppper** [antfu/shikiji#83]
### Clear and concise description of the problem

i want to get the background-color of the code theme without getting it from the dom

![image](https://github.com/antfu/shikiji/assets/93441520/60404061-b59c-4971-80a8-e64ce41b2ab9)

### Suggested solution

providing a var that have the velue of the background-color

### Alternative

.

### Additional context

Astro code block component

```astro
---
import type {
	BuiltinLanguage,
	BuiltinTheme,
	LanguageRegistration,
	SpecialLanguage,
	ThemeRegistration,
	ThemeRegistrationRaw,
} from 'shikiji';
import { getHighlighter } from "shikiji";

export interface Props {
	code: string;
	lang?: BuiltinLanguage | SpecialLanguage | LanguageRegistration;
	theme?: BuiltinTheme | ThemeRegistration | ThemeRegistrationRaw ;
}

const {
	code,
	lang = 'plaintext',
	theme = 'dark-plus',
} = Astro.props;

const shiki = await getHighlighter({
  themes: [theme],
  langs: [lang],
});

const codeOutput = shiki.codeToHtml(code, {
  lang:  lang as string,
  theme: theme,
});
---

<div class="code app dark">
  <div class="header">
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
  </div>
  <Fragment set:html={codeOutput} />
</div>

<script>
  const CodeEl = document.querySelector("pre.shiki");
  const CodeApp = document.querySelector(".code.app");
  CodeApp.style.backgroundColor = CodeEl.style.backgroundColor;
</script>
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can get it from `shiki.getTheme(themName).bg`
