### ISSUE TITLE
vitepress-plugin-twoslash: Unknown file extension ".css"

### ISSUE THREAD

**Issue by ocavue** [antfu/shikiji#86]
### Describe the bug

When using `vitepress-plugin-twoslash`, running `vitepress build` will throw the following error:

```
✓ building client + server bundles...
build error:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/projects/vite-astijb/node_modules/shikiji-twoslash/style-rich.css
```

While this error can be resolved by adding the config below in `.vitepress/config.ts`, I wonder if there is anyway to make `vitepress-plugin-twoslash` work without extra vite config. If no such way, maybe we could add some documentation to mention this vite config.

```
vite: {
  ssr: {
    // Uncomment the following line to fix the build
    noExternal: ['shikiji-twoslash', 'vitepress-plugin-twoslash'],
  },
}
```

### Reproduction

https://stackblitz.com/edit/vite-astijb

### System Info

```Shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XKyong** [comment]
👏  I appreciate that you mentioned this issue and provided a way to resolve it.

**Comment by Richard-Zhang1019** [comment]
Thanks bro, I met the issue when I build my program

**Comment by antfu** [comment]
Please update your usage by explicit putting the style file:
https://shikiji.netlify.app/packages/vitepress#twoslash
