### ISSUE TITLE
[markdown-it-shikiji]: Issues with line number highlights while using markdown-it-attrs

### ISSUE THREAD

**Issue by uncenter** [antfu/shikiji#88]
### Describe the bug

You cannot highlight lines with the `{1,3-4}` syntax if you also have `markdown-it-attrs` added as a plugin, since it uses the same curly bracket notation elsewhere. This is more of a proposal than a bug report - is it worth adding a note to the docs about how to resolve this? I figured out that I can [change the delimiter](https://github.com/arve0/markdown-it-attrs#custom-delimiters) of `markdown-it-attrs` from `{` and `}` to other characters to fix this, and I think other people might encounter this as well. On the topic of changing delimiters, that could be something we consider for the `markdown-it-shikiji` line number syntax as well.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You could disable it via: 
https://github.com/antfu/shikiji/blob/7620c7bc79783c6c2073596b3271d62b7e4b001e/packages/markdown-it-shikiji/src/core.ts#L7-L12

Would that be enough?

**Comment by uncenter** [comment]
I think you misunderstood what I meant ahah. I want the `highlightLines` feature, but it wasn't working at first because I had also been using `markdown-it-attrs`. I figured out a way to change the delimiter of `markdown-it-attrs`, which fixed the line highlighting feature. My suggestion is to maybe add a note on the markdown-it plugin page about this compatibility issue and potential ways to solve it.

**Comment by antfu** [comment]
Sure, I agree it's nice to note the compatibility in the docs. PR welcome if you want to work on that :)

**Comment by uncenter** [comment]
Great yeah, I'll make a PR in a sec :)
